services:
  app:
    build:
      context: .
    container_name: falinn-app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
      - TEST_DB_NAME=${TEST_DB_NAME}
    volumes:
      - ./src:/falinn/src
  
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh --eval 'db.runCommand({ ping: 1 })'"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/data/db

volumes:
  db_data: